
package com.company.jasperreportsdemo.dal;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;

import com.company.jasperreportsdemo.entities.Product;
import com.xdev.dal.JPADAO;

/**
 * Home object for domain model class Product.
 * 
 * @see Product
 */
public class ProductDAO extends JPADAO<Product, Integer> {
	public ProductDAO() {
		super(Product.class);
	}
	
	/**
	 * @queryMethod Do not edit, method is generated by editor!
	 */
	public List<Product> getProductsOrderedByCategory() {
		EntityManager entityManager = em();
	
		CriteriaBuilder criteriaBuilder = entityManager.getCriteriaBuilder();
	
		CriteriaQuery<Product> criteriaQuery = criteriaBuilder.createQuery(Product.class);
	
		Root<Product> root = criteriaQuery.from(Product.class);
	
		criteriaQuery.orderBy(criteriaBuilder.asc(root.get("category").get("categoryid")));
	
		TypedQuery<Product> query = entityManager.createQuery(criteriaQuery);
		return query.getResultList();
	}
}